sudo: required
services:
  - docker

before_install:
  - docker build -t jaiskiwi/docker-react -f Dockerfile.dev .

script:
  - echo "skipping tests"
  # - docker run -e CI=true jaiskiwi/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: 'ap-south-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-ap-south-1-157009564259'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
